version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: criminalistica_postgres
    environment:
      POSTGRES_DB: criminalistica_db
      POSTGRES_USER: criminalistica_user
      POSTGRES_PASSWORD: criminalistica_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U criminalistica_user -d criminalistica_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
